### ISSUE TITLE
Using CSS variables to update styles quickly

### ISSUE THREAD

**Issue by zannain** [jd-sims/f1-3-c2p1-colmar-academy#2]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is an important programming principle. If you find yourself repeating certain styles this is an indication that you can simplify your stylesheet by making use of CSS classes.

Rather than [applying](https://github.com/jd-sims/f1-3-c2p1-colmar-academy/blob/master/colmar_academy/resources/css/styles.css#L327-L329) the following styles multiple times. 

```css
display: none;
```

3. [Using CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)
```css
:root {
    --default-display: none;
}

#paint {
     display: var(--default-display);
}
```

CSS variables make it easy to update a style simultaneously by modifying that variable or the entire page is updated everywhere that variable is applied.
